# -*- coding: utf-8 -*-
"""object detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-hcdhPKx540W8xsdx9PoHM-OEp6mOYy
"""

# clone darknet repo
!git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
#enabling OPENCV GPU and CUDNN for our model in darkent
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile

#verify CUDA
!/usr/local/cuda/bin/nvcc --version

!make

#get yolo3 pretrained weights
!wget https://pjreddie.com/media/files/yolov3.weights

# Commented out IPython magic to ensure Python compatibility.
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image=cv2.imread(path)
  height,width=image.shape[:2]
  resized_image=cv2.resize(image,(6*height,3*width),interpolation=cv2.INTER_CUBIC)
  fig=plt.gcf()
  fig.set_size_inches(10,10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()


  #use this to upload files
def upload1():
  from google.colab import files
  uploaded=files.upload()
  for name, data in uploaded.items():
    with open(name,'wb') as f:
      f.write(data)
    print('saved file', name)
def download(path):
    from google.colab import files
    files.download(path)

!./darknet detect cfg/yolov3.cfg yolov3.weights data/person.jpg

imShow('predictions.jpg')

# Commented out IPython magic to ensure Python compatibility.
# %cd ..

upload1()

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!./darknet detect cfg/yolov3.cfg yolov3.weights ../street.jpg

imShow('predictions.jpg')

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
upload1()

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!./darknet detect cfg/yolov3.cfg yolov3.weights ../LW3637-01.jpg

imShow('predictions.jpg')

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
upload1()

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!./darknet detect cfg/yolov3.cfg yolov3.weights ../download\ \(1\).jfif

imShow('predictions.jpg')

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
upload1()

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!./darknet detect cfg/yolov3.cfg yolov3.weights ../social_image.jpg
imShow('predictions.jpg')



# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

download('predictions.jpg')

!cp predictions.jpg /mydrive/images_detection/abc.jpg

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
upload1()

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!./darknet detect cfg/yolov3.cfg yolov3.weights ../LW3637-01.jpg

imShow('predictions.jpg')

download('predictions.jpg')

